language: python            # this works for Linux but is an error on macOS or Windows
jobs:
  include:
    - name: "Python 3.8.0 on Xenial Linux"
      python: 3.8           # this works for Linux but is ignored on macOS or Windows
    - name: "Python 3.7.4 on macOS"
      os: osx
      osx_image: xcode11.2  # Python 3.7.4 running on macOS 10.14.4
      language: shell       # 'language: python' is an error on Travis CI macOS
install: 
  - python -m pip install --upgrade pip setuptools  # all three OSes agree about 'pip3'
  - python -m pip install --no-use-pep517 --editable .
# 'python3' is a 'command not found' error on Windows but 'py' works on Windows only
script: 
  - OMP_NUM_THREADS=2 python -m pytest
